// Generated by Frame. Keep behavior in separate files.
import 'dart:convert';
import 'package:flutter/material.dart';

class DesignSettings0 extends StatelessWidget {
  final Map<String, VoidCallback> actions;
  final Map<String, ValueChanged<String>> changes;
  final String? label, eventKey;
  final Color? background, foreground;
  final double? radius, fontSize, padding, gap, width, height;
  const DesignSettings0({
    super.key,
    this.actions = const {},
    this.changes = const {},
    this.label,
    this.eventKey,
    this.background,
    this.foreground,
    this.radius,
    this.fontSize,
    this.padding,
    this.gap,
    this.width,
    this.height,
  });
  @override
  Widget build(BuildContext context) => GestureDetector(
    behavior: HitTestBehavior.opaque,
    onTap: actions[(eventKey ?? '')],
    child: Container(
      width: width ?? null,
      height: height ?? null,
      padding: EdgeInsets.all((padding ?? 24)),
      decoration: BoxDecoration(
        color: (background ?? Colors.transparent),
        borderRadius: BorderRadius.circular((radius ?? 0)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        spacing: (gap ?? 18),
        children: [
          Container(
            padding: EdgeInsets.all(0),
            decoration: BoxDecoration(
              color: Colors.transparent,
              borderRadius: BorderRadius.circular(0),
            ),
            child: Text(
              'Your workspace',
              textAlign: TextAlign.left,
              style: TextStyle(
                fontSize: 28,
                fontFamily: null,
                fontWeight: FontWeight.w400,
                height: null,
                letterSpacing: 0,
                color: Color(0xFF20212A),
              ),
            ),
          ),
          Container(
            padding: EdgeInsets.all(0),
            decoration: BoxDecoration(
              color: Colors.transparent,
              borderRadius: BorderRadius.circular(0),
            ),
            child: Text(
              'Make it feel like you.',
              textAlign: TextAlign.left,
              style: TextStyle(
                fontSize: 16,
                fontFamily: null,
                fontWeight: FontWeight.w400,
                height: null,
                letterSpacing: 0,
                color: Color(0xFF20212A),
              ),
            ),
          ),
          Container(
            padding: EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Color(0xFFF2F0F7),
              borderRadius: BorderRadius.circular(16),
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              spacing: 12,
              children: [
                Container(
                  padding: EdgeInsets.all(0),
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    borderRadius: BorderRadius.circular(0),
                  ),
                  child: Text(
                    'Display name',
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      fontSize: 16,
                      fontFamily: null,
                      fontWeight: FontWeight.w400,
                      height: null,
                      letterSpacing: 0,
                      color: Color(0xFF20212A),
                    ),
                  ),
                ),
                Container(
                  padding: EdgeInsets.all(0),
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    borderRadius: BorderRadius.circular(0),
                  ),
                  child: TextField(
                    onChanged: changes['displayNameChanged'],
                    decoration: InputDecoration(
                      hintText: 'Enter a name',
                      border: const OutlineInputBorder(),
                    ),
                  ),
                ),
              ],
            ),
          ),
          DesignPrimarybutton2(
            actions: actions,
            changes: changes,
            label: 'Save \$ \'quoted\' \\ name',
            eventKey: 'savePreferences',
            background: Color(0xFF112233),
            radius: 8,
          ),
          Container(
            padding: EdgeInsets.all(0),
            decoration: BoxDecoration(
              color: Colors.transparent,
              borderRadius: BorderRadius.circular(0),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              spacing: 12,
              children: [
                Container(
                  padding: EdgeInsets.all(0),
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    borderRadius: BorderRadius.circular(0),
                  ),
                  child: Text(
                    'Ready',
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      fontSize: 16,
                      fontFamily: null,
                      fontWeight: FontWeight.w400,
                      height: null,
                      letterSpacing: 0,
                      color: Color(0xFF20212A),
                    ),
                  ),
                ),
                SizedBox(height: 24, width: 24),
              ],
            ),
          ),
        ],
      ),
    ),
  );
}

class DesignFidelity1 extends StatelessWidget {
  final Map<String, VoidCallback> actions;
  final Map<String, ValueChanged<String>> changes;
  final String? label, eventKey;
  final Color? background, foreground;
  final double? radius, fontSize, padding, gap, width, height;
  const DesignFidelity1({
    super.key,
    this.actions = const {},
    this.changes = const {},
    this.label,
    this.eventKey,
    this.background,
    this.foreground,
    this.radius,
    this.fontSize,
    this.padding,
    this.gap,
    this.width,
    this.height,
  });
  @override
  Widget build(BuildContext context) => GestureDetector(
    behavior: HitTestBehavior.opaque,
    onTap: actions[(eventKey ?? '')],
    child: ClipRRect(
      borderRadius: BorderRadius.circular((radius ?? 12)),
      child: Container(
        width: width ?? 120,
        height: height ?? 120,
        padding: EdgeInsets.all((padding ?? 0)),
        decoration: BoxDecoration(
          color: (background ?? Color(0xffffffff)),
          borderRadius: BorderRadius.circular((radius ?? 12)),
        ),
        child: SizedBox(
          width: (width ?? 120),
          height: (height ?? 120),
          child: Stack(
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 30,
                top: 25,
                child: GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTap: actions['artTapped'],
                  child: Container(
                    width: 20,
                    height: 20,
                    padding: EdgeInsets.all(0),
                    decoration: BoxDecoration(
                      color: Colors.transparent,
                      borderRadius: BorderRadius.circular(0),
                    ),
                    child: Image.memory(
                      base64Decode(
                        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1EAAAAASUVORK5CYII=',
                      ),
                      width: 20,
                      height: 20,
                      fit: BoxFit.fill,
                      filterQuality: FilterQuality.high,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 70,
                child: Container(
                  width: 60,
                  height: 20,
                  padding: EdgeInsets.all(0),
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    borderRadius: BorderRadius.circular(0),
                  ),
                  child: Semantics(
                    label: 'Hand drawn label',
                    child: Image.memory(
                      base64Decode(
                        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1EAAAAASUVORK5CYII=',
                      ),
                      width: 60,
                      height: 20,
                      fit: BoxFit.fill,
                      filterQuality: FilterQuality.high,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 5,
                top: 5,
                child: Container(
                  width: 20,
                  height: 20,
                  padding: EdgeInsets.all(0),
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    borderRadius: BorderRadius.circular(0),
                  ),
                  child: SizedBox(
                    width: 20,
                    height: 20,
                    child: Stack(
                      clipBehavior: Clip.none,
                      children: [
                        Positioned(
                          left: 3,
                          top: 5,
                          child: Container(
                            width: 5,
                            height: 5,
                            padding: EdgeInsets.all(0),
                            decoration: BoxDecoration(
                              color: Colors.transparent,
                              borderRadius: BorderRadius.circular(0),
                            ),
                            child: Image.memory(
                              base64Decode(
                                'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1EAAAAASUVORK5CYII=',
                              ),
                              width: 5,
                              height: 5,
                              fit: BoxFit.fill,
                              filterQuality: FilterQuality.high,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    ),
  );
}

class DesignPrimarybutton2 extends StatelessWidget {
  final Map<String, VoidCallback> actions;
  final Map<String, ValueChanged<String>> changes;
  final String? label, eventKey;
  final Color? background, foreground;
  final double? radius, fontSize, padding, gap, width, height;
  const DesignPrimarybutton2({
    super.key,
    this.actions = const {},
    this.changes = const {},
    this.label,
    this.eventKey,
    this.background,
    this.foreground,
    this.radius,
    this.fontSize,
    this.padding,
    this.gap,
    this.width,
    this.height,
  });
  @override
  Widget build(BuildContext context) => ElevatedButton(
    onPressed: actions[(eventKey ?? 'savePreferences')] ?? () {},
    style: ElevatedButton.styleFrom(
      backgroundColor: (background ?? Color(0xFF6750A4)),
      foregroundColor: (foreground ?? Color(0xFFFFFFFF)),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular((radius ?? 12)),
      ),
    ),
    child: Text((label ?? 'Save preferences')),
  );
}
