// Generated by Frame. Keep behavior in separate files.
import 'package:flutter/material.dart';

class DesignSettings0 extends StatelessWidget {
  final Map<String, VoidCallback> actions;
  final Map<String, ValueChanged<String>> changes;
  final String? label, eventKey;
  final Color? background, foreground;
  final double? radius, fontSize, padding, gap, width, height;
  const DesignSettings0({
    super.key,
    this.actions = const {},
    this.changes = const {},
    this.label,
    this.eventKey,
    this.background,
    this.foreground,
    this.radius,
    this.fontSize,
    this.padding,
    this.gap,
    this.width,
    this.height,
  });
  @override
  Widget build(BuildContext context) => Container(
    width: width ?? null,
    height: height ?? null,
    padding: EdgeInsets.all((padding ?? 24)),
    decoration: BoxDecoration(
      color: (background ?? Colors.transparent),
      borderRadius: BorderRadius.circular((radius ?? 0)),
    ),
    child: Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.start,
      spacing: (gap ?? 18),
      children: [
        Container(
          padding: EdgeInsets.all(0),
          decoration: BoxDecoration(
            color: Colors.transparent,
            borderRadius: BorderRadius.circular(0),
          ),
          child: Text(
            'Your workspace',
            style: TextStyle(fontSize: 28, color: Color(0xFF20212A)),
          ),
        ),
        Container(
          padding: EdgeInsets.all(0),
          decoration: BoxDecoration(
            color: Colors.transparent,
            borderRadius: BorderRadius.circular(0),
          ),
          child: Text(
            'Make it feel like you.',
            style: TextStyle(fontSize: 16, color: Color(0xFF20212A)),
          ),
        ),
        Container(
          padding: EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: Color(0xFFF2F0F7),
            borderRadius: BorderRadius.circular(16),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            spacing: 12,
            children: [
              Container(
                padding: EdgeInsets.all(0),
                decoration: BoxDecoration(
                  color: Colors.transparent,
                  borderRadius: BorderRadius.circular(0),
                ),
                child: Text(
                  'Display name',
                  style: TextStyle(fontSize: 16, color: Color(0xFF20212A)),
                ),
              ),
              Container(
                padding: EdgeInsets.all(0),
                decoration: BoxDecoration(
                  color: Colors.transparent,
                  borderRadius: BorderRadius.circular(0),
                ),
                child: TextField(
                  onChanged: changes['displayNameChanged'],
                  decoration: InputDecoration(
                    hintText: 'Enter a name',
                    border: const OutlineInputBorder(),
                  ),
                ),
              ),
            ],
          ),
        ),
        DesignPrimarybutton1(
          actions: actions,
          changes: changes,
          label: 'Save \$ \'quoted\' \\ name',
          eventKey: 'savePreferences',
          background: Color(0xFF112233),
          radius: 8,
        ),
        Container(
          padding: EdgeInsets.all(0),
          decoration: BoxDecoration(
            color: Colors.transparent,
            borderRadius: BorderRadius.circular(0),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            spacing: 12,
            children: [
              Container(
                padding: EdgeInsets.all(0),
                decoration: BoxDecoration(
                  color: Colors.transparent,
                  borderRadius: BorderRadius.circular(0),
                ),
                child: Text(
                  'Ready',
                  style: TextStyle(fontSize: 16, color: Color(0xFF20212A)),
                ),
              ),
              SizedBox(height: 24, width: 24),
            ],
          ),
        ),
      ],
    ),
  );
}

class DesignPrimarybutton1 extends StatelessWidget {
  final Map<String, VoidCallback> actions;
  final Map<String, ValueChanged<String>> changes;
  final String? label, eventKey;
  final Color? background, foreground;
  final double? radius, fontSize, padding, gap, width, height;
  const DesignPrimarybutton1({
    super.key,
    this.actions = const {},
    this.changes = const {},
    this.label,
    this.eventKey,
    this.background,
    this.foreground,
    this.radius,
    this.fontSize,
    this.padding,
    this.gap,
    this.width,
    this.height,
  });
  @override
  Widget build(BuildContext context) => ElevatedButton(
    onPressed: actions[(eventKey ?? 'savePreferences')] ?? () {},
    style: ElevatedButton.styleFrom(
      backgroundColor: (background ?? Color(0xFF6750A4)),
      foregroundColor: (foreground ?? Color(0xFFFFFFFF)),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular((radius ?? 12)),
      ),
    ),
    child: Text((label ?? 'Save preferences')),
  );
}
